### ISSUE TITLE
Text Domain Shouldn't be a Variable

### ISSUE THREAD

**Issue by benjamindejong** [postcode-nl/PostcodeNl_Api_WooCommerce#1]
Hi,

We like to translate the plugin, but the strings are not detected. This is because text domains shouldn't be a variable. Can you change that in the next release?

Use `__('Start typing the address', 'postcodenl-address-autocomplete')` 
instead of `__('Start typing the address', static::TEXT_DOMAIN)`.

More on that:
- [ https://github.com/DevinVinson/WordPress-Plugin-Boilerplate/issues/303](https://github.com/DevinVinson/WordPress-Plugin-Boilerplate/issues/303)
- [https://github.com/DevinVinson/WordPress-Plugin-Boilerplate/issues/59](https://github.com/DevinVinson/WordPress-Plugin-Boilerplate/issues/59)

**Comment by BastiaanGrutters** [comment]
Hi,

I've used poedit to generate and translate the plugin (partially), see [postcodenl-address-autocomplete-nl_NL.zip](https://github.com/postcode-nl/PostcodeNl_Api_WooCommerce/files/3983687/postcodenl-address-autocomplete-nl_NL.zip)
Perhaps you can use this until this issue is resolved.

As far as I've understood from your linked articles there are certain automated translation tools which have a problem with translation domain constants, but I'm not quite sure which. What translation tool are you using which is causing problems?

**Comment by benjamindejong** [comment]
I've used WP CLI i18n command and the plugin Loco Translate. They don't both recognize the translation domain constant.

**Comment by BastiaanGrutters** [comment]
Thanks, the translation domain will be changed to strings in the next version.

**Comment by JozefVerhoef** [comment]
This has been fixed in release 1.0.3 - thanks for the feedback!
